### PR TITLE
Adding npm to rest_api_gcbm/Dockerfile

### LINKED ISSUE #91: Add npm to rest_api_gcbm Dockerfile for CML actions
We sometimes use this image for running automated tests. There's an example of our CML workflow here: https://github.com/moja-global/GCBM.Belize/pull/7

Because the rest_api_gcbm image just a light wrapper over the standard GCBM build, I think it's ok to add npm here and save the installing it in every workflow. Please add npm to the rest_api_gcbm Dockerfile.

### PR DESCRIPTION
**Pull request by ankitaS11**
## Description

Fixes #91

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The Dockerfile is already used and tested. This PR just adds npm installation to it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

cc: @HarshCasper @aornugent

### CODE REVIEW

**Comment by aornugent** [comment]
Thanks @ankitaS11!

@HarshCasper - I can see Hadolint has some suggested changes, but these are not shown to the user. Is this the intended behaviour of the Lint action?

**Comment by HarshCasper** [comment]
> Thanks @ankitaS11!
> 
> @HarshCasper - I can see Hadolint has some suggested changes, but these are not shown to the user. Is this the intended behaviour of the Lint action?

For now, they are just warnings. We can ignore them for now.

**Comment by aornugent** [comment]
Huh, I thought the point of linting was to conform to best practices/style guide so it seems strange that it would suppress this feedback. But good if it catches breaking changes.

**Comment by HarshCasper** [comment]
> Huh, I thought the point of linting was to conform to best practices/style guide so it seems strange that it would suppress this feedback. But good if it catches breaking changes.

Yeah. The CI fails if serious warnings are found on Dockerfiles and they need to be fixed. The warnings and info labels are suppressed and we can hopefully fix them at a later stage.

**Pull request merged**
