### PR TITLE
feat root  endpoint added in rest_api_flint.example

### PR DESCRIPTION
**Pull request by USAMAWIZARD**
# Pull Request Template

## Description

root endpoint added in  rest_api_flint.example

## Type of change

Please delete options that are not relevant.

- [root endpoint added in api] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)
Screenshot (53)

...

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by chicken-biryani** [comment]
Hey, @USAMAWIZARD it would be great if you could open an issue before directly jumping to PRs?

**Comment by chicken-biryani** [comment]
@USAMAWIZARD can you please link it?

**Comment by USAMAWIZARD** [comment]
Use #116

**Comment by USAMAWIZARD** [comment]
#96

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
