### PR TITLE
Fixed bindings and explicitly only allows access from localhost

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #23

### CODE REVIEW

**Comment by iamrajiv** [comment]
@aornugent @shubhamkarande13 Can you take a look :)

**Comment by iamrajiv** [comment]
@aornugent @shubhamkarande13 Can you take a look :))

**Comment by arnav-t** [comment]
This change will break the layered API and cause the others to not function for qny requests outside of localhost.

**Comment by iamrajiv** [comment]
Thanks for the review @arnav-t. Did not think about layered API.

**Pull request closed without merging**
