### PR TITLE
feat: reference local path for inputs to run the GCBM example

### LINKED ISSUE #83: Reference local path of a volume in a docker container to process inputs
Currently, the inputs to the model at the `/gcbm/upload` route are uploaded via a `POST` request, through this issue, a docker volume mounted will be referenced and used to prepare the inputs for the model

### PR DESCRIPTION
**Pull request by Namyalg**
# Pull Request Template

## Description

This PR enables referencing a local path to supply inputs to the GCBM example. A volume is mounted onto the container, which is referenced in `app.py`. This eliminates the need to `POST` files at the `/gcbm/upload` endpoint.
The documentation has been updated accordingly.

Fixes #83 

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## How Has This Been Tested?
Testing has been performed by building the docker image and running the API endpoints

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review

### CODE REVIEW

**Comment by Namyalg** [comment]
@HarshCasper @aornugent , currently this works for the inputs, should this be extended to the output folder too?

**Comment by aornugent** [comment]
Hey @Namyalg -

Because FLINT.cloud can be run both locally and remotely, I think it might be better to introduce a second endpoint to change the path in the scenario where input files are mounted and available locally.

This way there would a user would have two options:
1. Set a local path and index any available input files
2. If there are no input files available, upload them to the app

Are you able to change this to leave the `upload` endpoint intact and have a second endpoint for indexing locally available files?

**Comment by Namyalg** [comment]
Yes, I think that can be achieved
I think the endpoint `/gcbm/upload/:option` will be able to handle both the cases 
1. `/gcbm/upload/local_path` (which means reference a mounted volume/or local path, as an example can be the unzipped version of GCBM_Demo_Run.zip)
2. `/gcbm/upload/app` (name can be changed) where the files can be uploaded directly

I was thinking, eliminating the need to POST files to the endpoint will make it easier and reduce the chance of errors as there might be a lot of files to upload (specifically talking about Postman as it does not support folder uploads)

**Comment by aornugent** [comment]
What if we had three endpoints:
1. `/path` - set the local file path where inputs are stored
2. `/check` - indexes any files that are stored in the local path
3. `/upload` - adds new files to the local path

There should be a sensible default for 1. so that users only need to call this endpoint if they need to change the path.

**Comment by Namyalg** [comment]
In my understanding, 
`/path` : create a directory if not existent, this will house the input folders (currently the input folder is expected to have `layers`, `input_database` and `config`)
`/check` : present the contents of the input folder
`/upload` : add files/folders to the directory referenced by `/path` (In case of a docker container, a volume could be mounted right at the start)

**Pull request closed without merging**
