### PR TITLE
docs: added instructions to interact with GCBM example endpoints using cURL

### LINKED ISSUE #85: Interact with GCBM endpoints using cURL
Presently, in the docs, interaction with the GCBM example endpoints is possible only using the Postman collection provided. I would like to provide a command-line alternative using cURL to interact with the endpoints.

### PR DESCRIPTION
**Pull request by Namyalg**
# Pull Request Template

## Description

This PR enables interaction with the GCBM endpoints using cURL. All endpoints listed are provided with a cURL alternative

Fixes #85 

## Type of change

Please delete options that are not relevant.
- [X] This change requires a documentation update

## How Has This Been Tested?

I have tested the commands on my cli and compared the results to the postman API collection 

## Checklist:

- [X] I have tagged the reviewers in a comment below incase my pull request is ready for a review

### CODE REVIEW

**Comment by Namyalg** [comment]
Along with the commands to interact with the endpoints, will it be a good idea to provide the expected output too?

**Review by aornugent — APPROVED** [review]

**Review by HarshCasper — CHANGES_REQUESTED** [review]
It would be better to adopt this doc into the Sphinx website so that its available to all the general users.

**Comment by Namyalg** [comment]
Okay, I will incorporate it into the sphinx documentation

**Comment by aornugent** [comment]
@HarshCasper - migrating to Sphinx sounds like a good GSoD issue. I don't think we have FLINTcloud up on docs.moja.global yet so maybe it can live here until we do?

**Comment by HarshCasper** [comment]
> @HarshCasper - migrating to Sphinx sounds like a good GSoD issue. I don't think we have FLINTcloud up on docs.moja.global yet so maybe it can live here until we do?

Sounds good to me!

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
