### PR TITLE
Add basic rest api project

### PR DESCRIPTION
**Pull request by Tlazypanda**
# Pull Request Template

## Description

Set up the basic project structure with endpoints: 

- help
- version
- help-section arg
- point_example from FLINT.example

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested locally

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by aornugent** [comment]
This looks great! Maybe @kaskou can review?

Would you mind documenting the steps involved in the wiki?

**Review by kaskou — COMMENTED** [review]
Looks good to me, not sure about the timeout issues which might occur from the server

**Comment by aornugent** [comment]
A thought for later: will it be possible / do we want to try to design a
generic endpoint, perhaps by passing config to specify which models should
be run, or would we expect users developing custom implementations to
specify an endpoint to match their modules?

We can discuss in our next design meeting.

**Comment by Tlazypanda** [comment]
@aornugent Updated the docs with a little bit of information on setup for now, plan to later make it more descriptive when the endpoints and all are perfectly in place. As for the generic endpoint Yes!! that's the plan too :raised_hands: Once we get all the endpoints done then we can provide this as well as other additional options to the user like letting them upload their own json file for computation. This is just the preliminary pr to get the basic structure done and we can start building on top of it.

**Pull request merged**
