### PR TITLE
feat: endpoint to rename a table

### LINKED ISSUE #174: Endpoint to modify table names
Currently, an endpoint to fetch the tables and their schema exist.
This endpoint should facilitate the modification of table names

### PR DESCRIPTION
**Pull request by Namyalg**
# Pull Request Template

## Description

This PR adds an endpoint to rename a table.

A post request is made as

```
 curl -d "title=run4&previous=old-table-name&new=new-table-name" -X POST http://localhost:8080/gcbm/table/rename
```

As an example, to change `turnover_parameter` to `new-turnover_parameter`

curl -d "title=run4&previous=turnover_parameter&new=new_turnover_parameter" -X POST http://localhost:8080/gcbm/table/rename

Fixes #174 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

image

### CODE REVIEW

**Comment by Namyalg** [comment]
@SanjaySinghRajpoot @YashKandalkar @ankitaS11 @padmajabhol, this is an implementation of the change table name endpoint

**Review by SanjaySinghRajpoot — APPROVED** [review]
LGTM!! Thanks for the changes.

**Comment by Namyalg** [comment]
Imo, this is iteration1, where we pass a single table, its old and new names. 
Maybe passing the old and new names as a dictionary might be a better idea ? in the case when more than 1 table needs to be changed?
Need more insight on how it will be implemented in the frontend

**Review by ankitaS11 — APPROVED** [review]

**Comment by ankitaS11** [comment]
Hi @Namyalg, this looks good for iteration 1.

**Comment by YashKandalkar** [comment]
LTGM! On the frontend we can have a Model open when a table name is clicked and the users can edit it's name. This way, only a single table name can be edited at a time. 
For column (or attribute) names we'd need an endpoint which accepts a dictionary as discussed earlier.

**Review by YashKandalkar — APPROVED** [review]

**Pull request merged**
