### PR TITLE
chore: moved get_config_templates, get_modules_cbm_config, get_pr…

### PR DESCRIPTION
**Pull request by khanjasir90**
…ovider_config to preprocess.py file

Signed-off-by: khanjasir90 <khanmohdjasir@gmail.com>

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change
refractor
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by khanjasir90** [comment]
@Namyalg could u review it once !

**Comment by Namyalg** [comment]
I will take a look

@khanjasir90, have you run the simulation with the refactored structure?

**Comment by khanjasir90** [comment]
@Namyalg no! since it was just a refractor change

**Comment by Namyalg** [comment]
I suggest you test run the simulation and share what you find

**Comment by khanjasir90** [comment]
@Namyalg just a doubt do i have to run the docker build command everytime I make changes to the code?

**Comment by khanjasir90** [comment]
@Namyalg ! after running the simulation I got the following response:
command exec : curl -d "title=run4" -X POST http://localhost:8080/gcbm/new
image

**Comment by Namyalg** [comment]
Yes, that's right 
Execute the endpoints,  `/gcbm/upload` and `/gcbm/dynamic` as mentioned in the curl.md file
If they dont throw any error, it means the PR is good to go

**Comment by khanjasir90** [comment]
@Namyalg curl to /gcmb/upload throughs the following error
image

**Comment by Namyalg** [comment]
Have you unzipped the contents of `GCBM_New_Demo_Run` and are executing the command from within that directory?

**Comment by khanjasir90** [comment]
@Namyalg oh my bad! i was'nt executing the commands for that directory.So sorry for disturbing you for small things.
After executing those command from that directory it works fine.
I have attached the ss of the same
image

**Comment by Namyalg** [comment]
Looks good.
Before the PR is merged, can you ensure the code is linted correctly using black https://github.com/psf/black

**Comment by khanjasir90** [comment]
@Namyalg linted the code using black.
image

**Comment by Namyalg** [comment]
Awesome, thanks a lot @khanjasir90

**Review by Namyalg — APPROVED** [review]

**Pull request merged**
