### PR TITLE
add gcbm dynamic endpoint with all config files upload ability

### LINKED ISSUE #5: Design Dynamic GCBM api endpoint
**Describe how we are communicating and why it is not optimal.**
As per the discussion on slack and from @mfellows and @aornugent suggestions, the gcbm endpoint has to be dynamic in nature. This entails all the - 

- config files: All files in config directory (.json and .cfg files)
- db: Input databse file (gcbm_input.db)
- input: All files in layers/tiled directory (.tif files)
 
 So the proposed solution is to have these as the parameters for the api endpoint and create a directory structure from this within the mounted volume (local run data shared by @mfellows). 
 
 Needs further discussion and work to properly perfect this to an extent that users find this pellucid.

### PR DESCRIPTION
**Pull request by Tlazypanda**
# Pull Request Template

## Description

Added gcbm   dynamic endpoint with all config files upload ability. Params are : 

- config files: All files in config directory (.json and .cfg files)
- db: Input databse file (gcbm_input.db)
- input: All files in layers/tiled directory (.tif files)

The curl call for this looks like - 

`curl --location --request POST 'http://0.0.0.0:8080/gcbm/dynamic' \
--header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
--header 'accept: application/json' \
--form 'db=@"/home/kalilinux/Documents/DistributedGCBMExample/Local_Run/input_database/gcbm_input.db"' \
--form 'title="example"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/variables.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/spinup.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/provider_config.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/pools_cbm.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/modules_output.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/modules_cbm.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/localdomain.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/internal_variables.json"' \
--form 'config_files=@"/home/kalilinux/Documents/DistributedGCBMExample/Distributed_Run/local_files/ExampleSimulation/config/gcbm_config.cfg"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/study_area.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/mean_annual_temperature_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/mean_annual_temperature_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/initial_age_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/initial_age_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/gcbm_input.db"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2018_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2018_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2016_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2016_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2015_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2015_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2014_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2014_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2013_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2013_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2012_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2012_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2011_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/disturbances_2011_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/Classifier2_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/Classifier2_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/Classifier1_moja.tiff"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/Classifier1_moja.json"' \
--form 'input=@"/home/kalilinux/Documents/GCBM/layers/tiled/bounding_box.tiff"'`

Response object looks like: 
`{
    "data": {
        "execTime": 127.81399297714233,
        "exitCode": 0,
        "response": "Operation executed successfully"
    }
}`

Fixes #5 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Locally

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by aornugent** [comment]
I'm not my idea makes sense, but one way to approach it would be to abstract the GCBM run from the upload endpoints. If we defined `/config`, `/input_database` and `/layers/tiled` such calls to POST or PUT uploaded one or more files into the correct folders.

Then you could simplify your final `/gcbm` call to either:
* first POST `/gcbm/config_file` + `gcbm/providers` files, setting an internal variable for each, then calling `/gcbm` to run the `moja.cli`

**Comment by mfellows** [comment]
Thanks Sneha!

My preference would probably be along the lines of Andrew's suggestion, especially because these simulations can potentially be pretty big; it's easier to resume an upload if you're doing a bunch of individual POSTs instead of a big monolithic one.

There's not really anything materially different from the input database and the spatial layers - in fact, there could theoretically be more than one database referenced by the provider file - so a more generic /data_files endpoint would be a little more flexible.

I don't think we should assume that a user will only be configuring one simulation at a time because that's a decision that really has some implications for the code, so my suggestion here is that we treat a simulation like a mutable container on the API side: maybe you POST the title to create a new one (and we can check that the title is unique, etc.), then PUT files into it until the client decides they're finished, then some endpoint for validation/running - we shouldn't really need to worry about session state.

**Comment by arnav-t** [comment]
Python script to generate a shell script to invoke the API using curl for given data.
Call from inside the folder containing the `config` and `layers` directories.
```python3
#!/usr/bin/python3

from os import listdir, chmod
from stat import ST_MODE, S_IEXEC, S_IREAD, S_IWRITE

SCRIPT = 'curl-api-call.sh'

header = '''#!/bin/bash

curl -X POST --location 'http://0.0.0.0:8080/gcbm/dynamic' \\
--header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \\
--header 'accept: application/json' \\
--form 'db=@"./input_database/gcbm_input.db"' \\
--form 'title="example"' \\
'''

with open(SCRIPT, 'w') as f:
  f.write(header)
  for file in listdir('./config'):
    f.write(f'--form \'config_files=@"./config/{file}"\' \\\n')
  for file in listdir('./layers/tiled'):
    f.write(f'--form \'input=@"./layers/tiled/{file}"\' \\\n')
  f.write('\n')

chmod(SCRIPT, ST_MODE | S_IEXEC | S_IREAD | S_IWRITE)
```

**Comment by aornugent** [comment]
@Tlazypanda - is this PR still active?

**Comment by Tlazypanda** [comment]
Nope @aornugent the changes for this covered in #7

**Pull request closed without merging**
