### PR TITLE
Renamed the endpoint dynamic to run

### PR DESCRIPTION
**Pull request by Saurabh-Suchak**
# Pull Request Template

Solves #149  

Renamed the `gcbm/dynamic` endpoint to `/gcbm/run`

### CODE REVIEW

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Can you also change the pytest for `/gcbm/run` ?

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Awesome, the simulation is working just fine. One small change, update the [curl command](https://github.com/moja-global/FLINT.Cloud/blob/master/local/rest_api_gcbm/curl.md) for `/dynamic`

**Review by padmajabhol — APPROVED** [review]

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Can you resolve the merge conflicts?

**Comment by aornugent** [comment]
Closing as stale - please reopen once reconciled with master.

**Pull request closed without merging**
