### PR TITLE
feat: Added title and Upload endpoints for GCBM Simulation

### PR DESCRIPTION
**Pull request by SanjaySinghRajpoot**
## Description
Created new endpoints to upload specific config files. As per the new FLINT-UI user will be able to upload config files separately. As per the discussion, we have decided to move forward with this implementation of the upload feature where a user has the ability to upload each file separately. Later each file from these folders will be used for pre processing.  
```
/upload/title
/upload/disturbances 
/upload/classifiers
/upload/miscellaneous
/upload/db
```

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested all the endpoints locally. 

@Namyalg @padmajabhol @ankitaS11 please review.

### CODE REVIEW

**Comment by Namyalg** [comment]
Looks good

**Comment by aornugent** [comment]
Hey @SanjaySinghRajpoot - this looks good. Can you please investigate why the tests are failing? @Namyalg might be able to help.

We might need new tests for this added functionality.

**Comment by Namyalg** [comment]
I believe it is failing due to some container scan vulnerabilities, the tests for the endpoints work fine
I'll see if I can fix it

**Comment by SanjaySinghRajpoot** [comment]
I will get in touch with @Namyalg regarding this CI build failure. I will also create new issue to added test cases for all the API endpoints.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Please add new tests for the implementation — The container scan check can be safely ignored (for now) as I will rip it off and replace it with a slightly friendlier option.

**Review by HarshCasper — APPROVED** [review]

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
