### PR TITLE
issue template for FLINT.Cloud

### PR DESCRIPTION
**Pull request by sailorworks**
I've made a issue template for FLINT.Cloud, as mentioned in the issue https://github.com/moja-global/FLINT.Cloud/issues/148 raised by @SanjaySinghRajpoot

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Review by SanjaySinghRajpoot — DISMISSED** [review]

**Comment by SanjaySinghRajpoot** [comment]
Thanks for the changes kindly sign your PR.

**Review by padmajabhol — DISMISSED** [review]

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Issue templates already exists here: https://github.com/moja-global/FLINT.Cloud/tree/master/.github/ISSUE_TEMPLATES

Why are we migrating to Markdown-based templates when YAML-based templates are better supported and provide a much better experience?

**Comment by sailorworks** [comment]
What should I do then, close this pull request??

**Comment by HarshCasper** [comment]
> What should I do then, close this pull request??

Yes

**Pull request closed without merging**
