### PR TITLE
Addressing issue #97

### LINKED ISSUE #97: Add `*.azurewebsites.net` to the CORS origin
## Description

Right now, we are getting CORS errors over the deployment of FLINT.Cloud and FLINT-UI. The error can be traced over to these references:

- FLINT.Example: https://github.com/moja-global/FLINT.Cloud/blob/da310e4efcd969c0dfe54f06f550fc2e37571571/local/rest_api_flint.example/app.py#L14
- REST API GCBM: https://github.com/moja-global/FLINT.Cloud/blob/da310e4efcd969c0dfe54f06f550fc2e37571571/local/rest_api_gcbm/app.py#L23

We need to add `*.azurewebsites.net` to this so that we can mitigate this issue.

### PR DESCRIPTION
**Pull request by tolusolaadeyemi**
# Pull Request Template

## Description

An 'env.template' file was created to assist contributors with some .env variables. The template was created particularly to address the CORS error raised in Issue #97. It contains all the CORS origins in a list inside the env variable 'CORS_ORIGINS.'  The origin '*.azurewebsites.net' was also added to help mitigate the issue. The python package 'python-decouple' was also installed to help access the env variables.

Fixes #97 

## File/Variable Creation

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings
- [x ] I have tagged the reviewers in a comment below incase my pull request is ready for a review

### CODE REVIEW

**Comment by tolusolaadeyemi** [comment]
@HarshCasper my PR is ready for review, whenever you get the chance. Thanks!

**Comment by shubhamkarande13** [comment]
Hi @tolusolaadeyemi !
We need to look into the merge conflict first to merge your changes.
Do you have any leads on how to resolve it?

**Comment by tolusolaadeyemi** [comment]
> Hi @tolusolaadeyemi! We need to look into the merge conflict first to merge your changes. Do you have any leads on how to resolve it?

Hey, I think I have resolved it but I'm not sure

**Comment by tolusolaadeyemi** [comment]
@HarshCasper , can you please review this PR

**Comment by tolusolaadeyemi** [comment]
@HarshCasper, can you please review this PR

**Pull request closed without merging**
